#!/bin/bash

# This is an attempt to recode the N(k)it™ framework for OSX for a much cleaner and easier interpretation.

# This version will be published as ver 2.0 of the N(k)it™ framework

# Let's start with declaring the local variables first.

home=$(echo $HOME) # Fetch the location of the home directory.
desktop=home/Desktop # Define the location of the desktop. ~/Desktop would have been an easier approach but was not used.
date=$(date "+%d-%m-%y") # This is the date in the Indian Style as DD-MM-YY for international standard use date=$(date "+%m-%d-%y").
time=$(date "+%T") # Get the time in HH:MM:SS format.
efilocation=/dev/disk0s1 # This is generally the location of EFI. Change it in case.
backupfolder=$desktop/Backup_On_$date # The location of the backup folder, date is added for multiple backups.
restorefolder=$desktop/Backup_On_$timestamp # The folder from which the data will be restored. $timestamp will be read by the restoration function.
efifolder=/Volumes/EFI/EFI/ # We will be using the diskutil approach to mount the fs so no more temp dir creation. Do not use /EFI it is more of a dummy folder for UEFI based install. Use that only on Clover Legacy.
clover=$efifolder/CLOVER # This is the location where the clover bootloader is generally installed. Change it if necessary.
dsdt=$clover/ACPI/patched/ # The location of all DSDTs and SSDTs.
config=$clover/*.plist # The location of all config files. Some users have some plists backup so we will count them in.
drivers=$clover/drivers64UEFI/ # The location of all clover drivers.
injectedkexts=$clover/kexts/ # The location of all (Ke)rnel E(xt)ensions.

# Location of folders on the backup directory. These are the folders where the data will be backed up.

dsdtbackup=$backupfolder/DSDT/
configbackup=$backupfolder/Configs/
driversbackup=$backupfolder/Clover_Drivers/
injectedkextsbackup=$backupfolder/Injected_Kexts/
slekextsbackup=$backupfolder/SLE_Kexts/

# As the restoration folder will differ. We will declare the same variables for restoration again with some difference.

dsdtrestore=$restorefolder/DSDT/
configrestore=$restorefolder/Configs/
driversrestore=$restorefolder/Clover_Drivers/
injectedkextsrestore=$restorefolder/Injected_Kexts/
slekextsrestore=$restorefolder/SLE_Kexts/

# We are done with the variables. If some fuction requires some variables they will be declared within the function's scope.

# Now we will declare the functions as i prefer writing a piece of code once instead of writing the same code over and over again.

function mountEFI()
{
	# Check if the volume is aready mounted.
	if [ -f /Volumes/EFI ];
		then 
		# Skip remount
		echo -e "Volume already mounted. Skipping remount."
	else
		# Mount the partition
		echo -e "Mounting EFI Partition."
		diskutil mount $efilocation &>/dev/null
	fi 
}

function unmountEFI()
{
	# Check if the volume is mounted. Then only attemp unmount.
	if [ -f /Volumes/EFI ];
		then
		# Unmount the volume
		diskutil unmount $efilocation &>/dev/null
		echo -e "Unmounted EFI Partition."
	else
		# Skip
		echo -e "Volume already unmounted."
	fi
}

function printHeader()
{
	echo N\(k\)it™ ver 1.0 by $author is running on $(sw_vers -productName) $(sw_vers -productVersion)
}

function printHelp()
{
	echo N\(k\)it™ ver 1.0 by $author is running on $(sw_vers -productName) $(sw_vers -productVersion)
	echo usage\: nkit [help]\|[-h] Prints help\(this\) information.
	echo \ \ \ \ \ \ \ nkit [backup]\|[-b] Generates a backup of important hackintosh files.
	echo \ \ \ \ \ \ \ nkit [restore]\|[-r] Restores the generated backup.
	echo \ \ \ \ \ \ \ nkit [efim]\|[-em] Mounts the EFI partition.
	echo \ \ \ \ \ \ \ nkit [efiu]\|[-eu] Unmounts the EFI Partition.
	echo \ \ \ \ \ \ \ nkit [prepareaft]\|[-aft] Revives Android File Transfer™ from death\-bed.
	echo \ \ \ \ \ \ \ nkit [unloadaft]\|[-uaft] Puts Android File Transfer™ to death\-bed.
}
